name: sunday_conversations
description: "Sunday Conversations for Flutter"
version: 0.1.5
homepage: https://github.com/sunday-team/sunday_conversations

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sunday_core: ^0.0.3
  uuid: ^4.5.1
  shared_preferences: ^2.3.5

dependency_overrides:
  shared_preferences_listener:
    path: ../shared_preferences_listener/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0