name: sunday_conversations
description: "Sunday Conversations for Flutter"
version: 0.0.2
homepage: https://github.com/sunday-team/sunday_conversations

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get_storage: ^2.1.1
  sunday_core: ^0.0.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0